# Generated by Django 3.2.10 on 2022-06-29 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='banner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPEG', 'GIF', 'PNG', 'APNG', 'SVG', 'BMP', 'ICO'])], verbose_name='Изображение')),
                ('Link', models.CharField(blank=True, max_length=50, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннер',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Image', models.FileField(blank=True, null=True, upload_to='service/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPEG', 'GIF', 'PNG', 'APNG', 'SVG', 'BMP', 'ICO'])], verbose_name='Изображение')),
                ('Description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
