# Generated by Django 3.2.10 on 2022-06-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Show',
            field=models.CharField(choices=[('Отображать', 'Отображать'), ('Не отображать', 'Не отображать')], default='Не отображать', max_length=50, verbose_name='Отображение'),
        ),
    ]
